name: tests/unit

on:
  push:
    branches: [staging]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [staging]
    paths:
      - 'lib/**'
      - 'arch/**'
      - 'include/**'
      - 'plat/**'
      - 'support/**'
      - '.github/workflows/pr-test.yaml'

jobs:
  test:
    name: test
    runs-on: ubuntu-latests
    strategy:
      fail-fast: false
      matrix:
        include:
        - ARCH: x86_64
          PLAT: qemu

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Fetch helloworld
      uses: actions/checkout@v2
      with:
        repository: unikraft/app-helloworld
        fetch-depth: 1
        path: _helloworld

    - name: Run libc-test via uktest
      uses: unikraft/kraftkit@staging
      with:
        loglevel: debug
        workdir: _helloworld
        execute: true
        kraftfile: |
          specification: '0.5'
          name: helloworld-test
          unikraft:
            source: ../
            kconfig:
              CONFIG_LIBUKTEST: "y"
              CONFIG_LIBUKTEST_ALL: "y"
              CONFIG_LIBUKDEBUG_ANSI_COLOR: "y"
              CONFIG_LIBDEVFS: "y"
              CONFIG_LIBDEVFS_DEV_STDOUT: "y"
              CONFIG_LIBDEVFS_DEV_NULL_ZERO: "y"
              CONFIG_LIBDEVFS_DEV_ZERO: "y"
              CONFIG_STACK_SIZE_PAGE_ORDER: 4
          libraries:
            libc-test:
              version: staging
              kconfig:
                CONFIG_LIBLIBCTEST: "y"
                CONFIG_LIBLIBCTEST_STRING_TESTS: "y"
                CONFIG_LIBLIBCTEST_PTHREAD_TESTS: "y"
                CONFIG_LIBLIBCTEST_CONVERSION_TESTS: "y"
                CONFIG_LIBLIBCTEST_REGEX_TESTS: "y"
                CONFIG_LIBLIBCTEST_FILE_FOLDER_TESTS: "y"
                CONFIG_LIBLIBCTEST_TIME_TESTS: "y"
                CONFIG_LIBLIBCTEST_NETWORK_TESTS: "y"
                CONFIG_LIBLIBCTEST_SORT_TESTS: "y"
                CONFIG_LIBLIBCTEST_STRUCTURE_SEARCH_TESTS: "y"
                CONFIG_LIBLIBCTEST_SEMAPHORE_TESTS: "y"
                CONFIG_LIBLIBCTEST_RANDOM_TESTS: "y"
                CONFIG_LIBLIBCTEST_CRYPT_TESTS: "y"
                CONFIG_LIBLIBCTEST_ENV_TESTS: "y"
                CONFIG_LIBLIBCTEST_MALLOC_TESTS: "y"
                CONFIG_LIBLIBCTEST_TGMATH_TESTS: "y"
                CONFIG_LIBLIBCTEST_ICONV_TESTS: "y"
                CONFIG_LIBLIBCTEST_UDIV_TESTS: "y"
                CONFIG_LIBLIBCTEST_MBFUNC_TESTS: "y"
                CONFIG_LIBLIBCTEST_SETJMP_TESTS: "y"
                CONFIG_LIBLIBCTEST_FPCLASSIFY_TESTS: "y"
                CONFIG_LIBLIBCTEST_POSIX_SPAWN_TESTS: "y"
                CONFIG_LIBLIBCTEST_ACCESS_TESTS: "y"
            musl:
              version: staging
              kconfig:
                CONFIG_MUSL: "y"
                CONFIG_LIBMUSL_COMPLEX: "y"
          targets:
          - architecture: ${{ matrix.ARCH }}
            platform: ${{ matrix.PLAT }}
